
- uses: 'google-github-actions/auth@v3'
  with:
    service_account: 'github-actions-sa@polars-bigquery.iam.gserviceaccount.com'
    workload_identity_provider: projects/700739494367/locations/global/workloadIdentityPools/github/providers/polars-bigquery-client
